module.exports = [
  { name: 'mcp_index_ticket', description: 'Index a Jira ticket: fetch its context, related tickets, Bitbucket branches/PRs and Confluence articles. Saves to local cache.', inputSchema: { type: 'object', properties: { ticketId: { type: 'string', description: 'Ticket key, e.g. ACME-123' } }, required: ['ticketId'] } },
  { name: 'mcp_get_ticket_context', description: 'Return the full cached context for a ticket (Jira details, Bitbucket branches/PRs, Confluence articles, timeline).', inputSchema: { type: 'object', properties: { ticketId: { type: 'string' } }, required: ['ticketId'] } },
  { name: 'mcp_sync_active_tickets', description: 'Re-index all currently cached tickets to refresh their context from Jira, Bitbucket and Confluence.', inputSchema: { type: 'object', properties: {} } },
  { name: 'mcp_list_cached_tickets', description: 'List all tickets that have been indexed and are stored in the local cache.', inputSchema: { type: 'object', properties: {} } },
  { name: 'mcp_get_agent_context', description: 'Return the full agent context document (teams, projects, Jira boards, and all cached ticket contexts).', inputSchema: { type: 'object', properties: {} } },
  { name: 'mcp_add_context_link', description: 'Manually add a context link (Confluence page, Jira epic, external URL) to a cached ticket.', inputSchema: { type: 'object', properties: { ticketId: { type: 'string' }, url: { type: 'string' }, title: { type: 'string', description: 'Optional label for the link' }, type: { type: 'string', description: 'confluence | jira | bitbucket | other (default: other)', enum: ['confluence', 'jira', 'bitbucket', 'other'] } }, required: ['ticketId', 'url'] } },
  { name: 'mcp_remove_ticket', description: 'Remove a ticket from the local cache.', inputSchema: { type: 'object', properties: { ticketId: { type: 'string' } }, required: ['ticketId'] } },
];
